remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "contrast" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
locale: "en-US"
title: "COSBO website"
subtitle: "COSBO"
name: "Kim-Anh Do, Ph.D."
description: A personal website"
url: "https://btseng22.github.io/KDo/"
repository: "btseng22/KDo"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  

head_scripts:
  - https://code.jquery.com/jquery-3.2.1.min.js

logo: "https://www.creativefabrica.com/wp-content/uploads/2022/10/29/1667046714/DNA-Icon-580x386.jpg"
masthead_title: "Kim-Anh Do, Ph.D."

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true

date_format: "%m-%d-%Y"

search: true
lunr:
  search_within_pages: true

og_image: "https://www.creativefabrica.com/wp-content/uploads/2022/10/29/1667046714/DNA-Icon-580x386.jpg"

social:
  type:  # Person or Organization (defaults to Person)
  name:  # If the user or organization name differs from the site's name
  links:
    - "https://www.linkedin.com/in/kim-anh-do-35b31463/"

author:
  name: "Kim-Anh Do, Ph.D."
  avatar: "./assets/images/KDoHeadshot.JPG"

  bio: "Pioneering Progress in Biostatistics and Cancer Research" # Note: Markdown is allowed
  
  location: "Houston, TX"
  links:
    - label: "My Website"
      icon: "https://faculty.mdanderson.org/profiles/kim-anh_do.html"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/kim-anh-do-35b31463/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single

defaults:
  # _foo
  - scope:
      path: ""
      type: foo
    values:
      layout: single

compress_html:
  clippings: all
  ignore:
    envs: development  # disable compression in dev environment

